In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [14]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9648148148148148

In [15]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.39444444444444443

In [16]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9740740740740741

In [18]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [19]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

(array([3, 4, 5, 6, 7, 8]), array([0, 1, 2]))
(array([0, 1, 2, 6, 7, 8]), array([3, 4, 5]))
(array([0, 1, 2, 3, 4, 5]), array([6, 7, 8]))


In [35]:
def get_score(model,x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [36]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [37]:
scores_1 = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
   x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
   scores_1.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
   scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
   scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

/home/lunawang/.local/lib/python2.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [38]:
scores_1

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [39]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [40]:
scores_rf

[0.8797996661101837, 0.9081803005008348, 0.8998330550918197]

In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

/home/lunawang/.local/lib/python2.7/site-packages/sklearn/model_selection/_split.py:2052: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.89534884, 0.94991653, 0.90939597])

In [43]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [44]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.89036545, 0.89482471, 0.88255034])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91362126, 0.94657763, 0.92281879])

In [46]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.85880399, 0.85642738, 0.87416107])

In [47]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.90863787, 0.91986644, 0.90771812])

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.93355482, 0.94490818, 0.93120805])